# Generated by Django 5.0.7 on 2024-07-17 10:53

from django.db import migrations


def forwards(apps, schema_editor):
    Client = apps.get_model("clients", "Client")
    Client.objects.bulk_create(
        [
            Client(name="John Doe"),
            Client(name="Bobby (drop) Tables"),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
    ]
